TERM=xterm-256color
LC_CTYPE=C
LANG=C
LC_ALL="en_US.UTF-8"

if [[ -z $HOSTNAME ]] then
    export CLOUDDESKTOP=0
else
    export CLOUDDESKTOP=1
fi

if [[ ${CLOUDDESKTOP} == 1 ]] then
    # Few things specific for CloudDesktop ZSH coming from envImprovement,
    # specifically /apollo/env/envImprovement/dotfiles/zshrc
    if [[ -z $TMUX ]]; then
        source $DOTFILESROOT/zsh/cloudart
    fi
    ENV_IMPROVEMENT_ROOT=/apollo/env/envImprovement
    module_path=($ENV_IMPROVEMENT_ROOT/var/lib/zsh/$ZSH_VERSION/)
    fpath=($ENV_IMPROVEMENT_ROOT/var/zsh/functions/$ZSH_VERSION        \
           $ENV_IMPROVEMENT_ROOT/var/share/zsh/$ZSH_VERSION/functions)

    export PATH=
    path=( ~/bin
           ~/usr/bin
           /usr/kerberos/bin
           ~/.toolbox/bin/
           /apollo/env/SDETools/bin
           /apollo/env/AmazonAwsCli/bin
           $ENV_IMPROVEMENT_ROOT/bin
           /usr/local/bin
           /usr/bin
           /bin
           /usr/sbin
           /sbin
           /usr/local/sbin
           /apollo/bin
           /apollo/sbin
           /apollo/env/ApolloCommandLine/bin)

    typeset -ga precmd_functions
    typeset -ga preexec_functions

    DISABLE_AUTO_UPDATE="true"
fi

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(zsh-autosuggestions zsh-syntax-highlighting autojump) # removed git from the list

ZSH_THEME="robbyrussell"

export ZSH=~/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

# override prompt
local ret_status="%(?:%{$fg_bold[green]%}#:%{$fg_bold[red]%}#)"
if [[ ${CLOUDDESKTOP} == 1 ]] then
    export PROMPT="${ret_status} %{$fg_bold[magenta]%}[空空空] %{$fg[cyan]%}%c %{$fg_bold[blue]%}> %{$reset_color%}"
else
    export PROMPT="${ret_status} %{$fg_bold[white]%}[Mac] %{$fg[cyan]%}%c %{$fg_bold[blue]%}> %{$reset_color%}"
fi

# Right prompt to show timestamp. See https://linux.die.net/man/1/zshmisc
RPROMPT="%{$fg_bold[blue]%}[%D{%Y/%m/%d} %*]%{$reset_color%}"

# Only set PATH if not in tmux - otherwise it duplicates entries
if [[ -z $TMUX ]]; then
    # Default MacOS path looks like this:
    # /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
    # Add a few things to it
    export PATH=$HOME/Documents/JS\ Documents/Personal/bin:$HOME/.toolbox/bin/:/apollo/env/SDETools/bin:/usr/local/opt/ruby/bin:/usr/local/bin:$PATH
fi

# Stars (*) are colored dark blue by default which is hard to see
if [[ ${CLOUDDESKTOP} != 1 ]] then
    ZSH_HIGHLIGHT_STYLES[globbing]=fg=blue,bold
fi

# When pasting text, no need to highlight
zle_highlight=('paste:none')
# Print an empty line between commands
precmd() { print "" }

# to see the key sequence, in terminal do Ctrl+V + key
bindkey '^n' autosuggest-accept
# yellow autosuggest text
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=226'

# completion of commands
zstyle ':completion:*' menu select
zstyle ':completion:*' group-name ''
zstyle ':completion:*' verbose yes
zstyle ':completion:*' list-colors '=(#b)*(XX *)=32=31' '=*=32'
zstyle ':completion:*:descriptions' format '%B%d%b'
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format 'No matches for: %d'
zstyle ':completion:*:corrections' format '%B%d (errors: %e)%b'

HYPHEN_INSENSITIVE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
# command execution time stamp shown in the `history` command output.
HIST_STAMPS="yyyy-mm-dd hh:MM:SS"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPS="--extended"
if [[ ${CLOUDDESKTOP} != 1 ]] then
    export FZF_DEFAULT_COMMAND="fd --type f --type l"  # fd is an alternative command, similar to find. If this var wasn't specified,
                                              # this is the command that would get executed:
                                              # https://github.com/junegunn/fzf/blob/16b5902aa278639fd99be89abe8ac50eb49b34aa/shell/key-bindings.zsh#L7-L10
fi
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
bindkey '^f' fzf-file-widget
bindkey '^y' fzf-cd-widget

# Quick vim startup
if [[ ${CLOUDDESKTOP} != 1 ]] then
    alias v=nvim
else
    alias v=vim
fi
if [[ ${CLOUDDESKTOP} != 1 ]] then
    alias tmuxnew='tmux -u new-session -s Mac \; source $DOTFILESROOT/tmux/dev.conf'
else
    alias tmuxnew='tmux -u new-session -s Cloud \; source $DOTFILESROOT/tmux/dev.conf'
fi
# c = Cloud
alias c='ssh dev-dsk-jhogue-2a-f2890d26.us-west-2.amazon.com'
alias tc='tmux attach-session -t Cloud'

# using Mac path to get app icon
alias alac="/Applications/Alacritty.app/Contents/MacOS/alacritty --config-file ~/dotfiles/alacritty/cloud.yml -e $SHELL -c 'ssh dev-dsk-jhogue-2b-264f79e6.us-west-2.amazon.com; $SHELL' &; disown"
alias alam='/Applications/Alacritty.app/Contents/MacOS/alacritty --config-file ~/dotfiles/alacritty/mac.yml &; disown'

alias odin="ssh -L 2009:localhost:2009 dev-dsk-jhogue-2b-264f79e6.us-west-2.amazon.com -f -N"

alias b=brazil-build
alias bs='brazil-build server'
alias bq='brazil-build quick_build'
alias bbit='brazil-build test-integration-assert'
alias bba='brazil-recursive-cmd --allPackages brazil-build'
alias bcl='brazil-build clean'
alias bca='brazil-recursive-cmd --allPackages --reverse brazil-build clean'
alias bvs='brazil vs'
alias bws='brazil ws'
alias sam="brazil-build-tool-exec sam"

alias gitlog="git log --all --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias gs='git status'
alias gb='git branch'
alias ga='git add .'
alias gc='git commit -m w '
alias gco='git status -s | fzf -m | cut -d" " -f3 | xargs git checkout'
alias gaf='git status -s | fzf -m | cut -d" " -f3 | xargs git add'
alias gsh='git show $(git log --pretty=oneline --abbrev-commit | fzf | cut -d " " -f 1)'
alias gr='git rebase -i HEAD~2'
alias gr3='git rebase -i HEAD~3'
alias gr4='git rebase -i HEAD~4'
alias gr5='git rebase -i HEAD~5'
alias gr6='git rebase -i HEAD~6'
alias gd='git diff'

if [[ ${CLOUDDESKTOP} != 1 ]] then
    alias less=bat
    alias cat=bat
fi

# Simple calculator which works by having node evaluate an expression
# Can be use like:
#   e "1+2"
e() {
    node -p "$1"
}

# Python stuff
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
export PATH=/opt/miniconda3/bin/:$PATH

# Add node (managed via nvm) to the path
lazynvm() {
  unset -f nvm node npm
  export NVM_DIR=~/.nvm
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
}

nvm() {
  lazynvm
  nvm $@
}

node() {
  lazynvm
  node $@
}

npm() {
  lazynvm
  npm $@
}
